encrypt-var NAME:
    ansible-vault encrypt_string --ask-vault-password --name {{ NAME }} --prompt

debug:
    ansible-playbook --inventory inventory.yml --ask-vault-pass debug-playbook.yml

limit HOST:
    ansible-playbook --inventory inventory.yml --ask-vault-pass --limit {{ HOST }} network-playbook.yml
